---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: jav-test
  namespace: dev
  annotations:
    flux.weave.works/tag.podinfod: semver:>3.0.0
    flux.weave.works/automated: 'true'
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jav-test
  template:
    metadata:
      labels:
        app: jav-test
      annotations:
        prometheus.io/scrape: 'true'
    spec:
      containers:
      - name: jav-test
        image: quay.io/brice/metrics-demo:master-a1560c8
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /readyz
            port: 9898
          initialDelaySeconds: 1
          periodSeconds: 5
          failureThreshold: 1
        livenessProbe:
          httpGet:
            path: /healthz
            port: 9898
          initialDelaySeconds: 1
          periodSeconds: 10
          failureThreshold: 2
        resources:
          requests:
            memory: "32Mi"
            cpu: "10m"

